In [1]:
import numpy as np
import pandas as pd
import random as ra
import numpy.matlib as nm
import numpy.linalg as na

**Q1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.**

In [12]:
arr=np.array((range(6)))
print(f"Numpy Array : {arr} \nData Type of Numpy Array {arr.dtype}")

Numpy Array : [0 1 2 3 4 5] 
Data Type of Numpy Array int64


**Q2. Given a NumPy array 'arr', check if its data type is float64.**

In [8]:
arr = np.array ([1.5, 2.6, 3.7])
if(arr.dtype==np.float64):
  print("The Numpy Array is of float64 type")
else:
  print("The Numpy Array is NOT of float64 type")

The Numpy Array is of float64 type


**Q3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.**

In [6]:
arr=np.array((5+6j,2+9j,4+7j),dtype=np.complex128)  # assigning dtype to to be complex128
print(f"Numpy Array of Complex128 datatype ---> {arr}")

Numpy Array of Complex128 datatype ---> [5.+6.j 2.+9.j 4.+7.j]


**Q4. Convert an existing NumPy array 'arr' of integers to float32 data type.**

In [7]:
arr=np.array(tuple(range(6)),dtype=np.int32)
print(f"Numpy Array of int32 type --> {arr}")
print(f"Numpy Array of float32 type --> {arr.astype(np.float32)}")

Numpy Array of int32 type --> [0 1 2 3 4 5]
Numpy Array of float32 type --> [0. 1. 2. 3. 4. 5.]


**Q5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.**

In [5]:
arr=np.array(tuple(range(6)),dtype=np.float64)
print(f"Before Changing the DataType ---> {arr.dtype}")
arr=arr.astype(np.float32)
print(f"After Changing the DataType ---> {arr.dtype}")

Before Changing the DataType ---> float64
After Changing the DataType ---> float32


**Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and DataType**

In [4]:
def array_attributes(my_arr):
  return({'shape':str(my_arr.shape),'size':str(my_arr.size),'Data_Type':str(my_arr.dtype)})

arr=np.random.randint(low=4,high=12,size=(3,4))
print(f"MetaData of the Array ---> \n {arr} : \n {array_attributes(arr)}")

MetaData of the Array ---> 
 [[ 9 11 11  7]
 [ 6 11  4  4]
 [10  9  8 11]] : 
 {'shape': '(3, 4)', 'size': '12', 'Data_Type': 'int64'}


**Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality**

In [3]:
def array_dimension(arr):
  return(arr.ndim)
arr=np.random.randint(low=4,high=12,size=(3,4))
print(f"The dimesonality of the Array : \n {arr} \n is = {array_dimension(arr)}D")

The dimesonality of the Array : 
 [[ 9  6  8 11]
 [11 10  7  4]
 [11  6 11  5]] 
 is = 2D


**Q8 Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.**

In [13]:
# Q8
def item_size(arr):
    return({'size':arr.size,'Total Size in Bytes':arr.nbytes})
    # Altenative method --> arr.itemsize*arr.size  (size of 1 element x the total numbers of elemnts)

arr=np.random.randint(4,10,size=(4,9))
print(f"{item_size(arr)}")

{'size': 36, 'Total Size in Bytes': 288}


**Q9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.**

In [10]:
# Q9
def array_strides(arr):
    return(arr.strides)

arr=np.random.randint(4,10,size=(4,9))
print(f"Stride of the Array \n {arr} \n In Bytes --> {array_strides(arr)}")

Stride of the Array 
 [[9 5 6 8 5 6 7 6 9]
 [9 9 8 4 8 6 6 5 6]
 [4 5 8 7 9 7 4 9 7]
 [8 4 6 5 4 8 5 5 8]] 
 In Bytes --> (72, 8)


**Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.**

In [14]:
# Q10
def shape_stride_relationship(arr):
    return({'Shape of Array':arr.shape,'Stride of the Array':arr.strides})


arr=np.random.randint(4,10,size=(4,9))
print(f"{shape_stride_relationship(arr)}")

{'Shape of Array': (4, 9), 'Stride of the Array': (72, 8)}


**Q11. Create a function create_zeros_array that takes an integer `n`as input and returns a NumPy array of zeros with 'n'elements.**

In [24]:
# Q11

def create_zeros_arrays(n):
    return(np.zeros(n))  # return an Numpy array of n elemnts filled with Zero's

print(f"Zero filled Array \n {create_zeros_arrays(12)}")

Zero filled Array 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Q12. Write a function create_ones_matrix that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols**

In [23]:
# Q12
def create_ones_matrix(row,col):
    return(np.ones((row,col)))  # returns a matrix filled with 1's

print(f"Ones filled Matrix \n {create_ones_matrix(row=2,col=5)}")

Ones filled Matrix 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Q13. Write a function 'generate_range_array' that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from 'start', ending at stop (exclusive), and with the specified step'.**

In [22]:
# Q13
def generate_range_array(start,stop,step=1):
    return(np.arange(start,stop,step))

print(f"Ranged Numpy Array  \n {generate_range_array(start=2,stop=10,step=2)}")

Ranged Numpy Array  
 [2 4 6 8]


**Q14. Design a function 'generate_linear_space' that takes two floats 'start', 'stop', and an integer 'num' as arguments and generates a NumPy array with num equally spaced values between 'start' and `stop (inclusive).**

In [21]:
# Q14
def generate_linear_space(num,start,stop):
    return np.linspace(start,stop,num)  # creating ecenly spaced intervals array

print(f"Line_spaced array : \n {generate_linear_space(10,3,10)}")


Line_spaced array : 
 [ 3.          3.77777778  4.55555556  5.33333333  6.11111111  6.88888889
  7.66666667  8.44444444  9.22222222 10.        ]


**Q15. Create a function create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n' using numpy.eye**

In [20]:
#Q15

def create_identity_matrix(n):
    return(np.eye(n,k=0))  # creating identity matrix using eye function
print(f"Identity Matrix : \n {create_identity_matrix(7)}")

Identity Matrix : 
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


**Q 16. Write a function that takes a Python list and converts it into a NumPy array.**

In [19]:
# Q16
import copy

def List_to_Numpyarray(lst):
    return(np.asarray(lst,dtype=np.float32))

my_lst=[45,23,96,45,85,12,20,3.3,45,69]
print(f"List version ---> {my_lst} \n Array Version : \n {List_to_Numpyarray(copy.deepcopy(my_lst))}")

List version ---> [45, 23, 96, 45, 85, 12, 20, 3.3, 45, 69] 
 Array Version : 
 [45.  23.  96.  45.  85.  12.  20.   3.3 45.  69. ]


**Q17. Create a NumPy array and demonstrate the use of `numpy.view' to create a new array object with the same data.**

In [18]:
# Q17

x=np.array([45,23,96,45,85,12,20,3.3,45,69],dtype=np.int16)
new_array=x.view()
print(f"New_Array_Object : {new_array}")

New_Array_Object : [45 23 96 45 85 12 20  3 45 69]


**Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.**

In [17]:
# Q18

def concatinate_axis(arr1,arr2):  #dunction to concatinate two arrays along the Horizontal Axis i.e axis=1
    return(np.hstack((arr1,arr2)))

arr1=np.random.randint(low=4,high=10,size=(3,2))
arr2=np.random.randint(low=4,high=10,size=(3,2))

print(f"Array 1 : \n {arr1} ,\n Array 2 : \n {arr2} , \n  Concatinate Along Horizontal Axis : \n {concatinate_axis(arr1,arr2)}")

Array 1 : 
 [[9 4]
 [4 4]
 [9 4]] ,
 Array 2 : 
 [[8 6]
 [7 6]
 [5 9]] , 
  Concatinate Along Horizontal Axis : 
 [[9 4 8 6]
 [4 4 7 6]
 [9 4 5 9]]


**Q19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy. concatenate`.**

In [16]:
# Q19
arr1=np.random.randint(low=4,high=10,size=(3,2))
arr2=np.random.randint(low=4,high=10,size=(2,3))
print(f"Array 1 : \n{arr1}")
print(f"\nArray 2 : {arr2}")

print(f"\nHorizontally Concatined Array : \n {np.hstack((arr1,arr2.T))}")

Array 1 : 
[[5 5]
 [6 6]
 [7 4]]

Array 2 : [[6 4 4]
 [4 9 8]]

Horizontally Concatined Array : 
 [[5 5 6 4]
 [6 6 4 9]
 [7 4 4 8]]


**Q20. Write a function that vertically stacks multiple NumPy arrays given as a list.**

In [25]:
#Q20
def vertical_Stack_Array(*args):
    return(np.vstack(args))  #stacking of all the lists

print(f"Multiple List's : {([45,20,36,89],[45,78,20,36],[13,79,39])}")
print(f"\nVertical Stacked Array of list : \n {vertical_Stack_Array([45,20,36,89],[45,78,20,36],[13,79,39,42])}")  # sendimng multiple lists as arguments

Multiple List's : ([45, 20, 36, 89], [45, 78, 20, 36], [13, 79, 39])

Vertical Stacked Array of list : 
 [[45 20 36 89]
 [45 78 20 36]
 [13 79 39 42]]


**Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.**

In [26]:
# Q21
def Arrange_NumpyArray(high,low=0,step=1):
    return(np.arange(low,high+1,step,dtype=np.int16))

print(f"Ranged Integer Array : {Arrange_NumpyArray(high=20,low=5,step=4)}")

Ranged Integer Array : [ 5  9 13 17]


**Q22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).**

In [27]:
# Q22
def EqualspacedValues_NumpyArray():
    return(np.linspace(start=0,stop=1,num=10))

print(f"Ranged Integer Array : {EqualspacedValues_NumpyArray()}")


Ranged Integer Array : [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).**


In [28]:
# Q23

def LogspacedValues_NumpyArray():
    return(np.logspace(start=1,stop=1000,num=5))

print(f"Ranged Integer Array : {LogspacedValues_NumpyArray()}")

Ranged Integer Array : [1.00000000e+001 5.62341325e+250             inf             inf
             inf]


/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


**Q24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.**

In [58]:
# Q24
arr=np.random.randint(low=1,high=101,size=(5,3))
df=pd.DataFrame(arr,columns=["A","B","C"])  #Pandas DataFrame created using Random integers between 1 to 100 using
df

A   B   C
0  86  68  52
1  48  48  51
2  23  83  78
3  73  86  93
4  92   9  10

**Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.**


In [30]:
# Q25
df=pd.DataFrame([[45,20,36],[-96,42,-9],[-12,-7,20]],columns=["A","B","C"])
print(f"Original DataFrame : \n {df}")
df["A"]=np.where(df["A"]<0,0,df["A"])  # (condition, True-Action , False Action)
# Alternative approach (wthout numpy)--> df["A"]=df["A"].apply(lambda x : 0 if(x<0) else x)
print(f"\n New DataFrameDataFrame : \n {df}")

Original DataFrame : 
     A   B   C
0  45  20  36
1 -96  42  -9
2 -12  -7  20

 New DataFrameDataFrame : 
     A   B   C
0  45  20  36
1   0  42  -9
2   0  -7  20


**Q26. Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50])**

In [31]:
#Q26
arr=np.array([10,20,30,40,50])
print(f"Accesing the 5th Element ---> {arr[4]}")

Accesing the 5th Element ---> 50


**Q27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])**


In [32]:
#Q27
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Fetching elemnt at (1,2) ---> {arr_2d[1,2]}")

Fetching elemnt at (1,2) ---> 6


**Q28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.arr = np.array([3, 8, 2, 10, 5, 7])**


In [33]:
#Q28
arr=np.array([3,8,2,10,5,7])
print(f"Elements Grater than 5 --> {arr[arr>5]}")

Elements Grater than 5 --> [ 8 10  7]


**Q29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. arr= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])**

In [34]:
# 29
arr=np.array([1,2,3,4,5,6,7,8,9])
print(f"Target Slicing --> {arr[2:6]}")  #extracting elements at index position from 2 to 5 inclusive

Target Slicing --> [3 4 5 6]


**Q30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]]` from the given array. arr_2d np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])**

In [35]:
# Q30
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Traget Extraction of Sub Array --> \n{arr_2d[0:2,1:3]}")

Traget Extraction of Sub Array --> 
[[2 3]
 [5 6]]


**Q31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.**

In [37]:
#Q31

def extract_index(arr,index):
    output_arr=np.empty(len(index),dtype=np.float16)  #Creating an empty array to store the extracted elements
    for i,ind in enumerate(index):
        if(0<=ind<arr.size):  #condition to check for out-of-bound indexes
            row,col=np.unravel_index(ind,arr.shape)
            output_arr[i]=arr[row,col]
        else:
            output_arr[i]=np.nan # Fill with Null if out of bound index takes place
    return output_arr

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
index = np.array([4, 1, 7])
print(f"Extracted Elements ---> {extract_index(array,index)}")

Extracted Elements ---> [5. 2. 8.]


**Q32. Create a NumPy function that filters elements greater than a threshold from a given ID array using boolean indexing.**

In [38]:
#Q32
arr=np.array((45,96,20,14,63,78,41,36,91,82,20,1,3,4,7))
threshold=12.5
print(f"Filtered Array --> {arr[arr>threshold]}")

Filtered Array --> [45 96 20 14 63 78 41 36 91 82 20]


**Q33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.**

In [39]:
#Q33
def ThreeD_Extraction(arr,a1,a2,a3):
    output=np.empty(len(a1))
    counter=0
    for i,j,k in (zip(a1,a2,a3)):
        try:
            output[counter]=arr[i,j,k]
        except ValueError:
            output[counter]=np.nan
        counter+=1
    return output

arr=np.random.randint(low=5,high=16,size=(2,3,3))
a1=np.random.randint(low=0,high=2,size=(5,))
a2=np.random.randint(low=0,high=3,size=(5,))
a3=np.random.randint(low=0,high=3,size=(5,))
print(f"Extracted Elements --> {ThreeD_Extraction(arr,a1,a2,a3)}")

Extracted Elements --> [ 7.  7. 13. 10. 12.]


**Q34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.**

In [40]:
#Q34

def Filter_Condition(arr):
    cond1,cond2=arr>(5**2),arr<(4**3)
    return(arr[cond1 & cond2])

arr=np.random.randint(low=14,high=70,size=(11,))
print(f"Array ---> {arr} \n Filtred Array ---> {Filter_Condition(arr)}")

Array ---> [56 62 53 55 55 63 35 20 45 43 23] 
 Filtred Array ---> [56 62 53 55 55 63 35 45 43]


**Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.**

In [41]:
#Q35

def Extraction_2D(arr,a1,a2):
    counter=0
    output=np.empty(min(len(a1),len(a2))) # Creating an array to store the extracted arrays
    for i,j in zip(a1,a2):
        try:
            output[counter]=arr[i,j]
        except IndexError:
            output[counter]=np.nan  #Fill with NULL values if IndexError occurs
        counter+=1
    return output

arr=np.random.randint(low=14,high=70,size=(11,3))
a1=np.random.randint(low=0,high=11,size=(ra.randint(10,20),))
a2=np.random.randint(low=0,high=3,size=(ra.randint(10,20),))
print(f"Original Array : \n {arr},\n Extracted Elements --> {Extraction_2D(arr,a1,a2)}")

Original Array : 
 [[43 67 57]
 [17 26 14]
 [16 48 62]
 [62 35 65]
 [38 66 34]
 [64 37 22]
 [64 19 25]
 [39 54 38]
 [61 53 51]
 [30 41 24]
 [44 64 23]],
 Extracted Elements --> [19. 26. 24. 35. 64. 24. 30. 66. 16. 25.]


**Q36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.**

In [42]:
#Q36
arr=np.random.randint(low=14,high=70,size=(3,3))
print(f"Original Array : \n {arr} ,\n Scalar addition of 5 : \n {arr+5}")

Original Array : 
 [[44 39 52]
 [58 38 49]
 [58 27 36]] ,
 Scalar addition of 5 : 
 [[49 44 57]
 [63 43 54]
 [63 32 41]]


**Q37. Consider two arrays arrl of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arrl using NumPy broadcasting.**

In [43]:
#Q37
arr1=np.random.randint(low=14,high=70,size=(1,3))
arr2=np.random.randint(low=14,high=70,size=(3,4))

for i in range(3):
    print(arr2[i]*arr1[0,i])

[3400 3740 1972 4148]
[3484  936 2808 3016]
[3276  832 2392 3224]


**Q38. Given a ID array arrl of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arrl to each row of arr2 using NumPy broadcasting.**

In [44]:
# Q38
arr1=np.random.randint(low=14,high=70,size=(1,4))
arr2=np.random.randint(low=14,high=70,size=(4,3))

for i in range(4):
    print(arr2[i]+arr1[0,i])

[44 66 65]
[112 106 108]
[37 74 79]
[77 41 65]


**Q39. Consider two arrays arrl of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.**

In [46]:
# Q39
arr1=np.random.randint(low=14,high=70,size=(3,1))
arr2=np.random.randint(low=14,high=70,size=(1,3))

print(f"Addition of Two Array Using Broadcasting {arr1+arr2.T}")

Addition of Two Array Using Broadcasting [[ 63]
 [ 85]
 [105]]


**Q40. Given arrays arrl of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.**

In [47]:
#40
arr1=np.random.randint(low=14,high=70,size=(2,3))
arr2=np.random.randint(low=14,high=70,size=(2,2))

#Trying to broadcasting of Multiplication with Incompatable shapes
try:
    print(arr1*arr2)
except ValueError:
    print("BROADCASTING NOT POSSIBLE DUE TO IN-COMPATABLE SHAPE")

BROADCASTING NOT POSSIBLE DUE TO IN-COMPATABLE SHAPE


**Q41. Calculate column-wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])**

In [68]:
#41
arr=np.array([[1,2,3],[4,5,6]])
for i in range(arr.shape[1]):
    print(f"Col{i+1} mean --> {arr[:,i].mean()}")

Col1 mean --> 2.5
Col2 mean --> 3.5
Col3 mean --> 4.5


**Q42. Find maximum value in each row of the given array: arr= np.array([[1, 2, 3], [4, 5, 6]])**

In [67]:
#Q42
arr=np.array([[1,2,3],[4,5,6]])
for i in range(arr.shape[0]):
    print(f"Max elemnt of Row{i+1} ---> {np.max(arr[i])}")

Max elemnt of Row1 ---> 3
Max elemnt of Row2 ---> 6


**Q43. For the given array, find indices of maximum value in each column.arr = np.array([[1, 2, 3], [4, 5, 6]])**


In [66]:
#Q43
arr=np.array([[1,2,3],[444,55,6]])
for i in range(arr.shape[1]):
    max=np.max(arr[:,i])
    print(f"Col{i+1} max element Index Position --> {np.where(arr==max)[0]}")

Col1 max element Index Position --> [1]
Col2 max element Index Position --> [1]
Col3 max element Index Position --> [1]


**Q44. For the given array, apply custom function to calculate moving sum along rows.arr = np.array([[1, 2, 3], [4, 5, 6]])**

In [65]:
#Q44
def custom_sum(row):
    return(sum(row))

arr=np.array([[1,2,3],[4,5,6]])
for i in range(arr.shape[0]):
    print(f"Sum of all the Row{i+1} elements ---> {custom_sum(arr[i])}")


Sum of all the Row1 elements ---> 6
Sum of all the Row2 elements ---> 15


**Q45. In the given array, check if all elements in each column are even.arr = np.array([[2, 4, 6], [3, 5, 7]])**

In [64]:
#Q45

arr=np.array([[2,4,6],[36,5,7]])
for i in range(arr.shape[1]):
    if(False in (arr[:,i]%2==0)):
        print(f"Col{i+1} contains a Odd Number")
    else:
        print(f"Col{i+1} contains only Even Numbers")

Col1 contains only Even Numbers
Col2 contains a Odd Number
Col3 contains a Odd Number


**Q46. Given a NumPy array arr, reshape it into a matrix of dimensions 'm' rows and `n` columns. Return the reshaped matrix.original_array = np.array([1, 2, 3, 4, 5, 6])**

In [63]:
#Q46
def Reshape(arr):
    m,n=ra.choice(((1,6),(6,1),(2,3),(3,2)))
    return arr.reshape(m,n)

original_array=np.array([1,2,3,4,5,6])
print(f"Original Array : \n{original_array}\nReshaped Array : \n{Reshape(original_array)}")

Original Array : 
[1 2 3 4 5 6]
Reshaped Array : 
[[1 2 3]
 [4 5 6]]


**Q47. Create a function that takes a matrix as input and returns the flattened array.input_matrix = np.array([[1, 2, 3], [4, 5, 6]])**

In [62]:
#Q47
def Flat_Array(mat):
    return(mat.flatten())

input_array=np.array([[1,2,3],[4,5,6]])
print(f"Original Array : \n{input_array}\nReshaped Array : \n{Flat_Array(input_array)}")

Original Array : 
[[1 2 3]
 [4 5 6]]
Reshaped Array : 
[1 2 3 4 5 6]


**Q48. Write a function that concatenates two given arrays along a specified axis.array1= np.array([[1, 2], [3, 4]])
array2= np.array([[5, 6], [7, 8]])**

In [61]:
#Q48
def Concatination(a1,a2):
    return np.concatenate((a1,a2),axis=ra.choice((0,1)))

array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])
print(f"Original Array1 : \n{array1}\nOriginal Array2 : \n{array2} \nConcatinated Array : \n{Concatination(array1,array2)}")

Original Array1 : 
[[1 2]
 [3 4]]
Original Array2 : 
[[5 6]
 [7 8]] 
Concatinated Array : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**Q49. Create a function that splits an array into multiple sub-arrays along a specified axis.original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])**


In [60]:
#Q49
def Split_Array(arr):
    return(np.split(arr,[1],axis=ra.choice((0,1))))

original_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Original Array : {original_array}\nSplitted Array's : \n {Split_Array(original_array)}")

Original Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Splitted Array's : 
 [array([[1, 2, 3]]), array([[4, 5, 6],
       [7, 8, 9]])]


**Q50. Write a function that inserts and then deletes elements from a given array at specified indices.**

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2,4]

values_to_insert [10, 11]

indices_to_delete = [1, 3]

In [59]:
#Q50
def Operations(arr,ind_i,val_i,ind_del):
    lst=list(arr)
    lst.insert(ind_i[0],val_i[0])
    lst.insert(ind_i[1],val_i[1])
    lst.pop(ind_del[0])
    lst.pop(ind_del[1])
    return(np.asarray(lst))


original_array=np.array([1,2,3,4,5])
indices_to_insert=[2,4]
values_to_insert=[10,11]
indices_to_delete=[1,3]

print(f"Original Array ---> {original_array}\nNew Array ---> {Operations(original_array,indices_to_insert,values_to_insert,indices_to_delete)}")

Original Array ---> [1 2 3 4 5]
New Array ---> [ 1 10  3  4  5]


**Q51. Create a NumPy array `arrl with random integers and another array 'arr2` with integers from 1 to 10. Perform element-wise addition between `arrl` and `arr2`.**

In [69]:
#Q51
arr1=np.random.randint(low=12,high=30,size=(10,))
arr2=np.array(range(1,11))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nAddition of Both Array --> {arr1+arr2}")

Array 1 --> [15 24 24 28 17 17 28 22 14 24]
Array 2 --> [ 1  2  3  4  5  6  7  8  9 10]
Addition of Both Array --> [16 26 27 32 22 23 35 30 23 34]


**Q52. Generate a NumPy array `arrl with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract arr2` from `arrl` element-wise.**

In [70]:
#Q52
arr1=np.array(range(10,0,-1))
arr2=np.array(range(1,11))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nSubtraction of Both Array --> {arr1-arr2}")

Array 1 --> [10  9  8  7  6  5  4  3  2  1]
Array 2 --> [ 1  2  3  4  5  6  7  8  9 10]
Subtraction of Both Array --> [ 9  7  5  3  1 -1 -3 -5 -7 -9]


**Q53. Create a NumPy array `arrl with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arrl` and `arr2`.**

In [71]:
#Q53
arr1=np.random.randint(low=12,high=30,size=(5,))
arr2=np.array(range(1,6))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nMultiplication of Both Array --> {arr1*arr2}")

Array 1 --> [19 16 21 19 19]
Array 2 --> [1 2 3 4 5]
Multiplication of Both Array --> [19 32 63 76 95]


**Q54. Generate a NumPy array `arrl with even integers from 2 to 10 and another array `arr2` with integers from i to 5. Perform element-wise division of `arrl by `arr2`.**

In [72]:
#Q54
arr1=np.array(range(2,11,2))
arr2=np.array(range(1,6))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nDivision of Both Array --> {arr1/arr2}")

Array 1 --> [ 2  4  6  8 10]
Array 2 --> [1 2 3 4 5]
Division of Both Array --> [2. 2. 2. 2. 2.]


**Q55. Create a NumPy array `arrl with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of arrl raised to the power of arr2 element-wise.**

In [73]:
#Q55
arr1=np.array(range(1,6))
arr2=np.array(range(5,0,-1))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nExponential of Both Array --> {arr1**arr2}")

Array 1 --> [1 2 3 4 5]
Array 2 --> [5 4 3 2 1]
Exponential of Both Array --> [ 1 16 27 16  5]


**Q56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.**

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [74]:
#Q56
counter=0
def Substring_Freq(st):
    target="he" #Target substring to look for in the Numpy strings
    global counter
    while(target in st):
        counter+=1  #counting the number of ocurrance of the substring
        st=st[((st.find(target))+len(target)):]

arr=np.array(["hello","world","hello","numpy","hello"])
for i in arr:
    Substring_Freq(i)

print(f"The Total Frequency of the substring he is ---> {counter}")

The Total Frequency of the substring he is ---> 3


**Q57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])**

In [75]:
#Q57
lst=""
def Extract_UpperCase(st):
    global lst
    lst=lst+"".join((filter(str.isupper,st)))

arr=np.array(['Hello', 'World', 'OpenAI', 'GPT'])
for i in arr:
    Extract_UpperCase(i)

print(f"Extracted UpperCase Characters from the Array of Strings ---> {arr} is ---> {tuple(lst)}")

Extracted UpperCase Characters from the Array of Strings ---> ['Hello' 'World' 'OpenAI' 'GPT'] is ---> ('H', 'W', 'O', 'A', 'I', 'G', 'P', 'T')


**Q58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.**



In [76]:
#Q58
def Replacement(st,target_str,sub_str):
    return (st.replace(sub_str,target_str))

arr=np.array(["apple","banana","grape","pineapple"]); sub_str="pple" ; target_str="GPT"
for i in arr:
    print(f"Original String --> {i} || New String --> {Replacement(i,target_str,sub_str)}")

Original String --> apple || New String --> aGPT
Original String --> banana || New String --> banana
Original String --> grape || New String --> grape
Original String --> pineapple || New String --> pineaGPT


**Q59. Write a function that concatenates strings in a NumPy array element-wise.**

* arr1=np.array(["Hello","World"],dtype="<U5")
* arr2=np.array(["Open","AI"],dtype="<U5")

In [77]:
#Q59

def Concatinate_String(a1,a2):
    return np.concatenate((a1,a2),axis=0)

arr1,arr2=np.array(["Hello","World"],dtype="<U5"),np.array(["Open","AI"],dtype="<U5")
#arr2.dtype
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\n Concatinated Array --> {Concatinate_String(arr1,arr2)}")

Array 1 --> ['Hello' 'World']
Array 2 --> ['Open' 'AI']
 Concatinated Array --> ['Hello' 'World' 'Open' 'AI']


**Q60. Write a function that finds the length of the longest string in a NumPy array.**
* arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [82]:
#Q60
def Longest_String_len(arr):
    return max(map(len,arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(f"Array --> {arr}\nLongest String Length = {Longest_String_len(arr)}")

Array --> ['apple' 'banana' 'grape' 'pineapple']
Longest String Length = [5, 6, 5, 9]


**Q61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.**

In [102]:
#Q61

df=pd.DataFrame(np.random.randint(low=1,high=1001,size=(100,)),columns=["Integers_Data"])
print(f"Mean\tMedian\tVarience\tStandard Deviation")
print(np.mean(df["Integers_Data"]),"\t",np.median(df["Integers_Data"]),"\t",np.var(df["Integers_Data"]),"\t",np.std(df["Integers_Data"]))

Mean	Median	Varience	Standard Deviation
475.12 	 466.5 	 86826.60559999997 	 294.6635464389852


**Q62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.**

In [101]:
#Q62
df=pd.DataFrame(np.random.randint(low=1,high=101,size=(50,)),columns=["Integers_Data"])
(df.describe()).loc[["25%","75%"]]

Integers_Data
25%           20.0
75%           80.0

**Q63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.**

In [ ]:
#Q63

**Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.**

In [100]:
#Q64
mat1,mat2=np.matrix(np.random.randint(low=1,high=11,size=(12,)).reshape(3,4)),np.matrix(np.random.randint(low=1,high=11,size=(16,)).reshape(4,4))
print(f"Matrix 1 : \n{mat1}\nMatrix 2 : \n{mat2}\n Dot Product : \n{np.dot(mat1,mat2)}")

Matrix 1 : 
[[ 3  7  6  3]
 [ 8  8  8 10]
 [ 6  7  5  5]]
Matrix 2 : 
[[10  8  7  9]
 [ 3  6  6 10]
 [ 6  3  8 10]
 [ 5  4  3  6]]
 Dot Product : 
[[102  96 120 175]
 [202 176 198 292]
 [136 125 139 204]]


**Q65 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.**

In [ ]:
#Q65



**Q66 Create a NumPy array of integers and find the index of a specific element.**

In [88]:
#Q66
arr_2d=np.array([[1,2,50],[4,54,5],[2,8,2]])

row=np.where(arr_2d.ravel()==5)
print(f"Row and Column coordinate {row}")

Row and Column coordinate (array([5]),)


**Q67 Generate a random NumPy array and sort it in ascending order.**

In [89]:
#Q67
arr=np.random.randint(low=5,high=20,size=(10,))
print(f"Unsorted Array --> {arr}\nSorted Array -->{np.sort(arr)}")

Unsorted Array --> [15 11 16  5 18 12  6 17 12 13]
Sorted Array -->[ 5  6 11 12 12 13 15 16 17 18]


**Q68 Filter elements >20 in the given NumPy array.**
* arr=np.array([12,25,6,42,8,30])

In [90]:
#Q68

arr=np.array([12,25,6,42,8,30])
print(f"Original Array--> {arr}\nFiltred Array >20 {arr[arr>20]}")

Original Array--> [12 25  6 42  8 30]
Filtred Array >20 [25 42 30]


**Q69. Filter elements which are divisible by 3 from a given NumPy array.**
arr=np.array([1,5,8,12,15])

In [91]:
#Q69

arr=np.array([1,5,8,12,15])
print(f"Original Array --> {arr}\nElements Div by 3-->{tuple(filter((lambda x: True if(x%3==0) else False),arr))}")

Original Array --> [ 1  5  8 12 15]
Elements Div by 3-->(12, 15)


**Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.**
arr=np.array([10,20,30,40,50])

In [ ]:
#Q70
arr=np.array([10,20,30,40,50])
print(f"Original Array --> {arr}\nElements ≥ 20 and ≤ 40-->{tuple(filter((lambda x: True if(x>=20 and x<=40) else False),arr))}")

Original Array --> [10 20 30 40 50]
Elements ≥ 20 and ≤ 40-->(20, 30, 40)


**Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.**
arr=np.array([1,2,3])

In [103]:
#Q71
arr=np.array([1,2,3])
print(f"Array-->{arr}\nByte Order-->{arr.dtype}")

Array-->[1 2 3]
Byte Order-->int64


**Q72. For the given NumPy array, perform byte swapping in place using `byteswap()`.**
np.array([1,2,3],dtype=np.int32)

In [104]:
#Q72

arr=np.array([1,2,3],dtype=np.int32)
print(f"Original byte order:{arr.dtype.byteorder}")

arr.byteswap()
print(f"Swapped byte order:{arr.dtype.byteorder}")

Original byte order:=
Swapped byte order:=


**Q75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.**

np.array([1,2,3],dtype=np.int32)

In [ ]:
#Q75


**Q76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.**

In [105]:
#Q76

arr1=np.random.randint(low=1,high=11,size=(10,))
copy_arr=np.copy(arr1)  #Creating a copy of the original array
print(f"Original Array Before Modification in copy --> {arr1}")
copy_arr[5]=7878  #Modification in copy
print(f"Original Array After Modification in copy --> {arr1}")  #No effect on Original Array

Original Array Before Modification in copy --> [ 1 10  3  7  6  2  9  1  5  5]
Original Array After Modification in copy --> [ 1 10  3  7  6  2  9  1  5  5]


**Q77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.**

In [106]:
#Q77

mat=np.asmatrix(np.random.randint(low=5,high=20,size=(3,3)))
print(f"Matrix Before Modifying View_Slice : \n{mat}")
view_slice=mat[0:2,0:2]  #Slicing the original matrix
view_slice[1,1]=9999  #Modifying an elemnt in View Slice
print(f"Matrix After Modifying View_Slice : \n{mat}") #Modification changes are reflected in the Original Matrix too

Matrix Before Modifying View_Slice : 
[[10 15  6]
 [14  8  7]
 [17  9  8]]
Matrix After Modifying View_Slice : 
[[  10   15    6]
 [  14 9999    7]
 [  17    9    8]]


**Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.**

In [107]:
#Q78

array_a=np.arange(1,13)
view_b=array_a[0:5]
print(f"Array A before broadcating --> {array_a}")
print(f"Broadcasting Addition of 5 to Array B --> {view_b+5}")
print(f"Array A After broadcating --> {array_a}")  #No changes where reflected

Array A before broadcating --> [ 1  2  3  4  5  6  7  8  9 10 11 12]
Broadcasting Addition of 5 to Array B --> [ 6  7  8  9 10]
Array A After broadcating --> [ 1  2  3  4  5  6  7  8  9 10 11 12]


**Q79.  Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.**

In [108]:
#Q79

orig_array=np.random.randint(low=1,high=9,size=(2,4))
reshaped_view=np.reshape(orig_array,(4,2))
print(f"Original Array : \n{orig_array}\nReshaped Array : \n{reshaped_view}")
reshaped_view[3,1]=-999  #Changing an elemnt in Reshaped_view array
print("\nAFTER MODIFICATION \n")
print(f"Original Array : \n{orig_array}\nReshaped Array : \n{reshaped_view}") #Modification changes are reflected in the Original Array too

Original Array : 
[[7 5 6 2]
 [6 4 6 7]]
Reshaped Array : 
[[7 5]
 [6 2]
 [6 4]
 [6 7]]

AFTER MODIFICATION 

Original Array : 
[[   7    5    6    2]
 [   6    4    6 -999]]
Reshaped Array : 
[[   7    5]
 [   6    2]
 [   6    4]
 [   6 -999]]


**Q80. create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data'**

In [109]:
#Q80
data=np.random.randint(low=1,high=20,size=(3,4))   #Creating an Array of Random integers of size 3x4
copy_data=data[data>5] #Creating a copy of the Filtred Array
print(data)
print("\n",copy_data)
copy_data[5]=777777  #Modifying an element in the copy_data array
print("\nAFTER MODIFICATION \n")
print("\n",data)  #No effect on the Original data Array

[[ 6  2 18  1]
 [11 14 18 15]
 [ 7 11 19 19]]

 [ 6 18 11 14 18 15  7 11 19 19]

AFTER MODIFICATION 


 [[ 6  2 18  1]
 [11 14 18 15]
 [ 7 11 19 19]]


**Q81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.**

In [110]:
#Q81
A,B=np.asmatrix(np.random.randint(low=5,high=20,size=(3,2))),np.asmatrix(np.random.randint(low=5,high=20,size=(3,2)))
print(f"Matrix 1: \n{A}\nMatrix 2 : \n{B}\nMatrix 1 + Matrix 2 : \n {A+B}\nMatrix 1 - Matrix 2 : \n {A-B}")

Matrix 1: 
[[ 8  8]
 [11  6]
 [ 5 14]]
Matrix 2 : 
[[17 14]
 [16 14]
 [ 7 12]]
Matrix 1 + Matrix 2 : 
 [[25 22]
 [27 20]
 [12 26]]
Matrix 1 - Matrix 2 : 
 [[-9 -6]
 [-5 -8]
 [-2  2]]


**Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.**

In [111]:
#Q82
C,D=np.asmatrix(np.random.randint(low=5,high=20,size=(3,2))),np.asmatrix(np.random.randint(low=5,high=20,size=(2,4)))
print(f"Matrix 1: \n{C}\nMatrix 2 : \n{D}\n Matrix 1 X Matrix 2 : \n {C@D}")

Matrix 1: 
[[14  5]
 [10  9]
 [16  5]]
Matrix 2 : 
[[15 11 15 14]
 [10 10 19 16]]
 Matrix 1 X Matrix 2 : 
 [[260 204 305 276]
 [240 200 321 284]
 [290 226 335 304]]


**Q83. Create a matrix `E` and find its transpose**

In [112]:
#Q83
E=np.asmatrix(np.random.randint(low=5,high=20,size=(4,3)))
print(f"Matrix : \n{E}\n Transpose_of_Matrix : \n{E.T}")

Matrix : 
[[12 18 10]
 [13 12 16]
 [ 7 16 14]
 [ 6  8  7]]
 Transpose_of_Matrix : 
[[12 13  7  6]
 [18 12 16  8]
 [10 16 14  7]]


**Q84. Generate a square matrix `F` and compute its determinant.**

In [113]:
#Q84
F=np.asmatrix(np.random.randint(low=5,high=20,size=(3,3)))
print(f"Matrix : \n{F}\n Determinant_of_Matrix : \n{na.det(F)}")

Matrix : 
[[10 14 14]
 [ 8 11 12]
 [19 11 13]]
 Determinant_of_Matrix : 
152.0


**Q85. Create a square matrix `G` and find its inverse.**

In [114]:
#Q85
G=np.matrix(np.random.randint(low=5,high=12,size=(3,3)))
print(f"Matrix : \n{G}\n Inverse_of_Matrix : \n{na.inv(G)}")

Matrix : 
[[ 7 10 10]
 [10 11  7]
 [ 6  9  8]]
 Inverse_of_Matrix : 
[[ 0.71428571  0.28571429 -1.14285714]
 [-1.08571429 -0.11428571  1.45714286]
 [ 0.68571429 -0.08571429 -0.65714286]]
